name: Build Site

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install Node Dependencies
        run: npm install

      - name: Build Website
        run: npm run docs:build
