name: Release Site

on:
  workflow_dispatch:
    inputs:
      release_branch:
        type: string
        description: 'Branch to release'
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    environment: production
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.release_branch }}

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install Node Dependencies
        run: npm install

      - name: Build Website
        run: npm run docs:build

      - name: Deploy to cloudflare pages
        uses: cloudflare/wrangler-action@v3
        with:
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy .vitepress/dist --project-name="docs-flexpilot-ai"
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
